// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppMenu: typeof import('./components/app/AppMenu.vue')['default']
    Footer: typeof import('./components/app/Footer.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Submenu: typeof import('./components/app/Submenu.vue')['default']
    Topbar: typeof import('./components/app/Topbar.vue')['default']
  }
}

export { }
